[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn api_server:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
